// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppSMC.h>
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// SMC_Ricker
Rcpp::List SMC_Ricker(arma::vec data, unsigned long outN, unsigned long inN, arma::vec temperatures);
RcppExport SEXP _RickerExample_SMC_Ricker(SEXP dataSEXP, SEXP outNSEXP, SEXP inNSEXP, SEXP temperaturesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type data(dataSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type outN(outNSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type inN(inNSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type temperatures(temperaturesSEXP);
    rcpp_result_gen = Rcpp::wrap(SMC_Ricker(data, outN, inN, temperatures));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RickerExample_SMC_Ricker", (DL_FUNC) &_RickerExample_SMC_Ricker, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_RickerExample(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
